### ISSUE TITLE
Add Custom JSON Marshaller to Pubkey

### ISSUE THREAD

**Issue by oten91** [pokt-network/posmint#149]

**Comment by oten91** [comment]
We need a custom marshaller for pubkey

**Comment by andrewnguyen22** [comment]
Is this for the accounts field?

**Comment by oten91** [comment]
> Is this for the accounts field?

Currently changing it application wide for Ed25519PublicKey, account seems fine but when marshaling  the public key field is marshaling recursively as its underlying type []byte @andrewnguyen22
