### ISSUE TITLE
Staking too little results in a 0 power validator

### ISSUE THREAD

**Issue by andrewnguyen22** [pokt-network/posmint#99]
If you stake too little, the power of your validator is 0 which should never be able to happen
See: 
```
// TokensToConsensusPower - convert input tokens to potential consensus-engine power
func TokensToConsensusPower(tokens Int) int64 {
	return (tokens.Quo(PowerReduction)).Int64()
}

```

**Comment by oten91** [comment]
Will be increasing the minimun stake to workaround this
`	DefaultMinStake                    int64  = 1000000
`
